export const imageCollections = {
  artify: [
    { url: "artify/captura-01.jpg", title: "artify-01" },
    { url: "artify/captura-02.jpg", title: "artify-02" },
    { url: "artify/captura-03.jpg", title: "artify-03" },
    { url: "artify/captura-04.jpg", title: "artify-04" },
  ],
  pokedex: [
    { url: "pokedex/captura-01.jpg", title: "pokedex-01" },
    { url: "pokedex/captura-02.jpg", title: "pokedex-02" },
    { url: "pokedex/captura-03.jpg", title: "pokedex-03" },
    { url: "pokedex/captura-04.jpg", title: "pokedex-04" },
    { url: "pokedex/captura-05.jpg", title: "pokedex-05" },
    { url: "pokedex/captura-06.jpg", title: "pokedex-06" },
    { url: "pokedex/captura-07.jpg", title: "pokedex-07" },
  ],
  rym: [
    { url: "rym/captura-01.jpg", title: "rym-01" },
    { url: "rym/captura-02.jpg", title: "rym-02" },
    { url: "rym/captura-03.jpg", title: "rym-03" },
    { url: "rym/captura-04.jpg", title: "rym-04" },
  ],
  sesc: [
    { url: "sesc/captura-01.jpg", title: "sesc-01" },
    { url: "sesc/captura-02.jpg", title: "sesc-02" },
    { url: "sesc/captura-03.jpg", title: "sesc-03" },
    { url: "sesc/captura-04.jpg", title: "sesc-04" },
    { url: "sesc/captura-05.jpg", title: "sesc-05" },
  ],
  ibis: [
    { url: "ibis/captura-01.jpg", title: "ibis-01" },
    { url: "ibis/captura-02.jpg", title: "ibis-02" },
    { url: "ibis/captura-03.jpg", title: "ibis-03" },
    { url: "ibis/captura-04.jpg", title: "ibis-04" },
    { url: "ibis/captura-05.jpg", title: "ibis-05" },
    { url: "ibis/captura-06.jpg", title: "ibis-06" },
    { url: "ibis/captura-07.jpg", title: "ibis-07" },
    { url: "ibis/captura-08.jpg", title: "ibis-08" },
    { url: "ibis/captura-09.jpg", title: "ibis-09" },
  ],
};
